# generated by datamodel-codegen:
#   filename:  discworld.yaml
#   timestamp: 2026-05-04T08:30:36+00:00

from __future__ import annotations
from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel, conint, constr
from enum import Enum
from datetime import date
from typing import Any


class GroupdetailModel(BaseModel):
    url: AnyUrl
    label: constr(max_length=4096) | None = None


class GrouplistModel(BaseModel):
    url: AnyUrl
    label: constr(max_length=4096) | None = None


class HistoryTypeEnum(Enum):
    field_ = "+"
    field__1 = "~"
    field__2 = "-"


class MinimalEntity(BaseModel):
    uri: AnyUrl
    name: str


class PaginatedGrouplistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[GrouplistModel]


class PersondetailModel(BaseModel):
    url: AnyUrl
    forename: constr(max_length=4096) | None = None
    surname: constr(max_length=4096) | None = None
    gender: constr(max_length=4096) | None = None
    date_of_birth: date | None = None
    date_of_death: date | None = None
    profession: list[AnyUrl] | None = None


class PersonlistModel(BaseModel):
    url: AnyUrl
    forename: constr(max_length=4096) | None = None
    surname: constr(max_length=4096) | None = None
    gender: constr(max_length=4096) | None = None
    date_of_birth: date | None = None
    date_of_death: date | None = None
    profession: list[AnyUrl] | None = None


class PlacedetailModel(BaseModel):
    url: AnyUrl
    label: constr(max_length=4096) | None = None
    latitude: float | None = None
    longitude: float | None = None
    feature_code: constr(max_length=16) | None = Field(
        None,
        description='<a href="https://www.geonames.org/export/codes.html" target="_blank">Geonames Feature Code List</a>',
    )


class PlacelistModel(BaseModel):
    url: AnyUrl
    label: constr(max_length=4096) | None = None
    latitude: float | None = None
    longitude: float | None = None
    feature_code: constr(max_length=16) | None = Field(
        None,
        description='<a href="https://www.geonames.org/export/codes.html" target="_blank">Geonames Feature Code List</a>',
    )


class ProfessiondetailModel(BaseModel):
    url: AnyUrl
    name: constr(max_length=1024) | None = None


class ProfessionlistModel(BaseModel):
    url: AnyUrl
    name: constr(max_length=1024) | None = None


class RootObjectdetailModel(BaseModel):
    url: AnyUrl


class RootObjectlistModel(BaseModel):
    url: AnyUrl


class SimpleObject(BaseModel):
    url: AnyUrl
    label: str
    content_type_key: str
    content_type_name: str


class SkosCollectionContentObjectdetailModel(BaseModel):
    url: AnyUrl
    object_id: conint(ge=0, le=9223372036854775807)
    collection: AnyUrl
    content_type: AnyUrl


class SkosCollectionContentObjectlistModel(BaseModel):
    url: AnyUrl
    object_id: conint(ge=0, le=9223372036854775807)
    collection: AnyUrl
    content_type: AnyUrl


class SkosCollectiondetailModel(BaseModel):
    url: AnyUrl
    name: constr(max_length=300) = Field(
        ..., description="Collection label or name", title="Skos:prefLabel"
    )
    label_lang: constr(max_length=3) | None = Field(
        None,
        description="Language of preferred label given above",
        title="Skos:prefLabel language",
    )
    creator: str | None = Field(
        None,
        description="Person or organisation that created this collectionIf more than one list all using a semicolon ;",
        title="Dc:creator",
    )
    contributor: str | None = Field(
        None,
        description="Person or organisation that made contributions to the collectionIf more than one list all using a semicolon ;",
        title="Dc:contributor",
    )


class SkosCollectionlistModel(BaseModel):
    url: AnyUrl
    name: constr(max_length=300) = Field(
        ..., description="Collection label or name", title="Skos:prefLabel"
    )
    label_lang: constr(max_length=3) | None = Field(
        None,
        description="Language of preferred label given above",
        title="Skos:prefLabel language",
    )
    creator: str | None = Field(
        None,
        description="Person or organisation that created this collectionIf more than one list all using a semicolon ;",
        title="Dc:creator",
    )
    contributor: str | None = Field(
        None,
        description="Person or organisation that made contributions to the collectionIf more than one list all using a semicolon ;",
        title="Dc:contributor",
    )


class UridetailModel(BaseModel):
    url: AnyUrl
    uri: AnyUrl | None = None
    object_id: conint(ge=0, le=9223372036854775807) | None = None
    content_type: AnyUrl | None = None


class UrilistModel(BaseModel):
    url: AnyUrl
    uri: AnyUrl | None = None
    object_id: conint(ge=0, le=9223372036854775807) | None = None
    content_type: AnyUrl | None = None


class VersionGroupdetailModel(BaseModel):
    url: AnyUrl
    id: conint(ge=-9223372036854775808, le=9223372036854775807) | None = None
    label: constr(max_length=4096) | None = None
    history_date: AwareDatetime
    history_change_reason: constr(max_length=100) | None = None
    history_type: HistoryTypeEnum
    rootobject_ptr: AnyUrl | None = None
    history_user: AnyUrl | None = None


class VersionGrouplistModel(BaseModel):
    url: AnyUrl
    id: conint(ge=-9223372036854775808, le=9223372036854775807) | None = None
    label: constr(max_length=4096) | None = None
    history_date: AwareDatetime
    history_change_reason: constr(max_length=100) | None = None
    history_type: HistoryTypeEnum
    rootobject_ptr: AnyUrl | None = None
    history_user: AnyUrl | None = None


class VersionPersondetailModel(BaseModel):
    url: AnyUrl
    id: conint(ge=-9223372036854775808, le=9223372036854775807) | None = None
    forename: constr(max_length=4096) | None = None
    surname: constr(max_length=4096) | None = None
    gender: constr(max_length=4096) | None = None
    date_of_birth: date | None = None
    date_of_death: date | None = None
    history_date: AwareDatetime
    history_change_reason: constr(max_length=100) | None = None
    history_type: HistoryTypeEnum
    rootobject_ptr: AnyUrl | None = None
    history_user: AnyUrl | None = None


class VersionPersonlistModel(BaseModel):
    url: AnyUrl
    id: conint(ge=-9223372036854775808, le=9223372036854775807) | None = None
    forename: constr(max_length=4096) | None = None
    surname: constr(max_length=4096) | None = None
    gender: constr(max_length=4096) | None = None
    date_of_birth: date | None = None
    date_of_death: date | None = None
    history_date: AwareDatetime
    history_change_reason: constr(max_length=100) | None = None
    history_type: HistoryTypeEnum
    rootobject_ptr: AnyUrl | None = None
    history_user: AnyUrl | None = None


class VersionPlacedetailModel(BaseModel):
    url: AnyUrl
    id: conint(ge=-9223372036854775808, le=9223372036854775807) | None = None
    label: constr(max_length=4096) | None = None
    latitude: float | None = None
    longitude: float | None = None
    feature_code: constr(max_length=16) | None = Field(
        None,
        description='<a href="https://www.geonames.org/export/codes.html" target="_blank">Geonames Feature Code List</a>',
    )
    history_date: AwareDatetime
    history_change_reason: constr(max_length=100) | None = None
    history_type: HistoryTypeEnum
    rootobject_ptr: AnyUrl | None = None
    history_user: AnyUrl | None = None


class VersionPlacelistModel(BaseModel):
    url: AnyUrl
    id: conint(ge=-9223372036854775808, le=9223372036854775807) | None = None
    label: constr(max_length=4096) | None = None
    latitude: float | None = None
    longitude: float | None = None
    feature_code: constr(max_length=16) | None = Field(
        None,
        description='<a href="https://www.geonames.org/export/codes.html" target="_blank">Geonames Feature Code List</a>',
    )
    history_date: AwareDatetime
    history_change_reason: constr(max_length=100) | None = None
    history_type: HistoryTypeEnum
    rootobject_ptr: AnyUrl | None = None
    history_user: AnyUrl | None = None


class VersionProfessiondetailModel(BaseModel):
    url: AnyUrl
    id: conint(ge=-9223372036854775808, le=9223372036854775807) | None = None
    name: constr(max_length=1024) | None = None
    history_date: AwareDatetime
    history_change_reason: constr(max_length=100) | None = None
    history_type: HistoryTypeEnum
    history_user: AnyUrl | None = None


class VersionProfessionlistModel(BaseModel):
    url: AnyUrl
    id: conint(ge=-9223372036854775808, le=9223372036854775807) | None = None
    name: constr(max_length=1024) | None = None
    history_date: AwareDatetime
    history_change_reason: constr(max_length=100) | None = None
    history_type: HistoryTypeEnum
    history_user: AnyUrl | None = None


class ApiDumpdataRetrieveParametersQuery(BaseModel):
    app_labels: list[str] | None = None


class ApiEntitiesListParametersQuery(BaseModel):
    search: str | None = None


class ApiEntitiesListResponse(RootModel[list[MinimalEntity]]):
    root: list[MinimalEntity]


class Format(Enum):
    json = "json"
    yaml = "yaml"


class Lang(Enum):
    af = "af"
    ar = "ar"
    ar_dz = "ar-dz"
    ast = "ast"
    az = "az"
    be = "be"
    bg = "bg"
    bn = "bn"
    br = "br"
    bs = "bs"
    ca = "ca"
    ckb = "ckb"
    cs = "cs"
    cy = "cy"
    da = "da"
    de = "de"
    dsb = "dsb"
    el = "el"
    en = "en"
    en_au = "en-au"
    en_gb = "en-gb"
    eo = "eo"
    es = "es"
    es_ar = "es-ar"
    es_co = "es-co"
    es_mx = "es-mx"
    es_ni = "es-ni"
    es_ve = "es-ve"
    et = "et"
    eu = "eu"
    fa = "fa"
    fi = "fi"
    fr = "fr"
    fy = "fy"
    ga = "ga"
    gd = "gd"
    gl = "gl"
    he = "he"
    hi = "hi"
    hr = "hr"
    hsb = "hsb"
    ht = "ht"
    hu = "hu"
    hy = "hy"
    ia = "ia"
    id = "id"
    ig = "ig"
    io = "io"
    is_ = "is"
    it = "it"
    ja = "ja"
    ka = "ka"
    kab = "kab"
    kk = "kk"
    km = "km"
    kn = "kn"
    ko = "ko"
    ky = "ky"
    lb = "lb"
    lt = "lt"
    lv = "lv"
    mk = "mk"
    ml = "ml"
    mn = "mn"
    mr = "mr"
    ms = "ms"
    my = "my"
    nb = "nb"
    ne = "ne"
    nl = "nl"
    nn = "nn"
    os = "os"
    pa = "pa"
    pl = "pl"
    pt = "pt"
    pt_br = "pt-br"
    ro = "ro"
    ru = "ru"
    sk = "sk"
    sl = "sl"
    sq = "sq"
    sr = "sr"
    sr_latn = "sr-latn"
    sv = "sv"
    sw = "sw"
    ta = "ta"
    te = "te"
    tg = "tg"
    th = "th"
    tk = "tk"
    tr = "tr"
    tt = "tt"
    udm = "udm"
    ug = "ug"
    uk = "uk"
    ur = "ur"
    uz = "uz"
    vi = "vi"
    zh_hans = "zh-hans"
    zh_hant = "zh-hant"


class SwaggerSchemaRetrieveParametersQuery(BaseModel):
    format: Format | None = None
    lang: Lang | None = None


class SwaggerSchemaRetrieveResponse(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class ApiSampleProjectGroupListParametersQuery(BaseModel):
    label: str | None = None
    limit: int | None = None
    offset: int | None = None


class ApiSampleProjectIscousinofListParametersQuery(BaseModel):
    limit: int | None = None
    obj_search: str | None = None
    offset: int | None = None
    subj_search: str | None = None


class ApiSampleProjectIsparentofListParametersQuery(BaseModel):
    limit: int | None = None
    obj_search: str | None = None
    offset: int | None = None
    subj_search: str | None = None


class ApiSampleProjectIspartofListParametersQuery(BaseModel):
    limit: int | None = None
    obj_search: str | None = None
    offset: int | None = None
    subj_search: str | None = None


class ApiSampleProjectIssiblingofListParametersQuery(BaseModel):
    limit: int | None = None
    obj_search: str | None = None
    offset: int | None = None
    subj_search: str | None = None


class ApiSampleProjectLivesinListParametersQuery(BaseModel):
    limit: int | None = None
    obj_search: str | None = None
    offset: int | None = None
    subj_search: str | None = None


class ApiSampleProjectPersonListParametersQuery(BaseModel):
    date_of_birth: date | None = None
    date_of_death: date | None = None
    forename: str | None = None
    gender: str | None = None
    limit: int | None = None
    offset: int | None = None
    profession: list[int] | None = None
    surname: str | None = None


class ApiSampleProjectPlaceListParametersQuery(BaseModel):
    feature_code: str | None = None
    label: str | None = None
    latitude: float | None = None
    limit: int | None = None
    longitude: float | None = None
    offset: int | None = None


class ApiSampleProjectProfessionListParametersQuery(BaseModel):
    limit: int | None = None
    name: str | None = None
    offset: int | None = None


class HistoryType(Enum):
    field_ = "+"
    field__1 = "-"
    field__2 = "~"


class ApiSampleProjectVersiongroupListParametersQuery(BaseModel):
    history_change_reason: str | None = None
    history_date: AwareDatetime | None = None
    history_type: HistoryType | None = None
    history_user: int | None = None
    id: int | None = None
    label: str | None = None
    limit: int | None = None
    offset: int | None = None


class ApiSampleProjectVersionpersonListParametersQuery(BaseModel):
    date_of_birth: date | None = None
    date_of_death: date | None = None
    forename: str | None = None
    gender: str | None = None
    history_change_reason: str | None = None
    history_date: AwareDatetime | None = None
    history_type: HistoryType | None = None
    history_user: int | None = None
    id: int | None = None
    limit: int | None = None
    offset: int | None = None
    surname: str | None = None


class ApiSampleProjectVersionplaceListParametersQuery(BaseModel):
    feature_code: str | None = None
    history_change_reason: str | None = None
    history_date: AwareDatetime | None = None
    history_type: HistoryType | None = None
    history_user: int | None = None
    id: int | None = None
    label: str | None = None
    latitude: float | None = None
    limit: int | None = None
    longitude: float | None = None
    offset: int | None = None


class ApiSampleProjectVersionprofessionListParametersQuery(BaseModel):
    history_change_reason: str | None = None
    history_date: AwareDatetime | None = None
    history_type: HistoryType | None = None
    history_user: int | None = None
    id: int | None = None
    limit: int | None = None
    name: str | None = None
    offset: int | None = None


class ApiCollectionsSkoscollectionListParametersQuery(BaseModel):
    contributor: str | None = None
    creator: str | None = None
    label_lang: str | None = None
    limit: int | None = None
    name: str | None = None
    offset: int | None = None


class ApiCollectionsSkoscollectioncontentobjectListParametersQuery(BaseModel):
    collection: int | None = None
    content_type: int | None = None
    limit: int | None = None
    object_id: int | None = None
    offset: int | None = None


class ApiApisMetainfoRootobjectListParametersQuery(BaseModel):
    limit: int | None = None
    offset: int | None = None


class ApiUrisUriListParametersQuery(BaseModel):
    content_type: int | None = None
    limit: int | None = None
    object_id: int | None = None
    offset: int | None = None
    uri: str | None = None


class ApiRelationsRelationListParametersQuery(BaseModel):
    limit: int | None = None
    obj_search: str | None = None
    offset: int | None = None
    subj_search: str | None = None


class IsCousinOfdetailModel(BaseModel):
    url: AnyUrl
    subj: SimpleObject
    obj: SimpleObject


class IsCousinOflistModel(BaseModel):
    url: AnyUrl
    subj: SimpleObject
    obj: SimpleObject


class IsParentOfdetailModel(BaseModel):
    url: AnyUrl
    subj: SimpleObject
    obj: SimpleObject


class IsParentOflistModel(BaseModel):
    url: AnyUrl
    subj: SimpleObject
    obj: SimpleObject


class IsPartOfdetailModel(BaseModel):
    url: AnyUrl
    subj: SimpleObject
    obj: SimpleObject


class IsPartOflistModel(BaseModel):
    url: AnyUrl
    subj: SimpleObject
    obj: SimpleObject


class IsSiblingOfdetailModel(BaseModel):
    url: AnyUrl
    subj: SimpleObject
    obj: SimpleObject


class IsSiblingOflistModel(BaseModel):
    url: AnyUrl
    subj: SimpleObject
    obj: SimpleObject


class LivesIndetailModel(BaseModel):
    url: AnyUrl
    subj: SimpleObject
    obj: SimpleObject


class LivesInlistModel(BaseModel):
    url: AnyUrl
    subj: SimpleObject
    obj: SimpleObject


class PaginatedIsCousinOflistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[IsCousinOflistModel]


class PaginatedIsParentOflistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[IsParentOflistModel]


class PaginatedIsPartOflistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[IsPartOflistModel]


class PaginatedIsSiblingOflistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[IsSiblingOflistModel]


class PaginatedLivesInlistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[LivesInlistModel]


class PaginatedPersonlistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[PersonlistModel]


class PaginatedPlacelistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[PlacelistModel]


class PaginatedProfessionlistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[ProfessionlistModel]


class PaginatedRootObjectlistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[RootObjectlistModel]


class PaginatedSkosCollectionContentObjectlistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[SkosCollectionContentObjectlistModel]


class PaginatedSkosCollectionlistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[SkosCollectionlistModel]


class PaginatedUrilistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[UrilistModel]


class PaginatedVersionGrouplistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[VersionGrouplistModel]


class PaginatedVersionPersonlistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[VersionPersonlistModel]


class PaginatedVersionPlacelistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[VersionPlacelistModel]


class PaginatedVersionProfessionlistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[VersionProfessionlistModel]


class RelationdetailModel(BaseModel):
    url: AnyUrl
    subj: SimpleObject
    obj: SimpleObject


class RelationlistModel(BaseModel):
    url: AnyUrl
    subj: SimpleObject
    obj: SimpleObject


class PaginatedRelationlistModelList(BaseModel):
    count: int = Field(..., examples=[123])
    next: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=400&limit=100"]
    )
    previous: AnyUrl | None = Field(
        None, examples=["http://api.example.org/accounts/?offset=200&limit=100"]
    )
    results: list[RelationlistModel]
